services:
  odoo:
    build: .
    container_name: tk-odoo
    user: odoo
    ports:
      - "8069:8069"
    tty: true
    env_file:
      - .env
    environment:
      ODOO_DB_HOST: ${ODOO_DB_HOST:-localhost}
      ODOO_DB_PORT: ${ODOO_DB_PORT:-5432}
      ODOO_DB_USER: ${ODOO_DB_USER:-odoo}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - ./config/odoo.conf.template:/etc/odoo/odoo.conf.template
      - ./src/addons:/mnt/addons
      - ./src/extra-addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo

    command: >
      bash -c "
        envsubst < /etc/odoo/odoo.conf.template > /etc/odoo/odoo.conf &&
        odoo -d odoo -u all --without-demo=all --stop-after-init &&
        odoo -d odoo --without-demo=all
      "

volumes:
  odoo-data:
