services:
  db:
    image: postgres:16-alpine
    container_name: tk-odoo-db
    environment:
      POSTGRES_USER: ${ODOO_DB_USER:-odoo}
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
      POSTGRES_DB: postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ODOO_DB_USER:-odoo}"]
      interval: 5s
      timeout: 5s
      retries: 5

  odoo:
    build: .
    container_name: tk-odoo
    user: odoo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "5678:5678"
    tty: true
    env_file:
      - .env
    environment:
      ODOO_DB_HOST: db
      ODOO_DB_PORT: 5432
      ODOO_DB_USER: ${ODOO_DB_USER:-odoo}
      ODOO_DB_PASSWORD: ${ODOO_DB_PASSWORD:-odoo}
    volumes:
      - ./config/odoo.conf.template:/etc/odoo/odoo.conf.template
      - ./src/addons:/mnt/addons
      - ./src/extra-addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo

    command: >
      bash -c "
        envsubst < /etc/odoo/odoo.conf.template > /etc/odoo/odoo.conf &&
        python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m odoo -d odoo -u all --without-demo=all --stop-after-init &&
        python3 -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m odoo -d odoo --without-demo=all
      "

volumes:
  odoo-data:
  odoo-db-data: